#!/usr/bin/env python3
"""Regenerate fixtures/conformance.json from the Python implementation.

Both test suites assert against this file, so any behavior difference between
the TypeScript and Python packages fails one of them. CI regenerates the file
and fails when the committed copy is stale.

Usage: uv run --project packages/python python scripts/generate_conformance.py
"""

from __future__ import annotations

import json
import random
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages" / "python" / "src"))

import poder as rut  # noqa: E402

FIXTURE = ROOT / "fixtures" / "conformance.json"

BOUNDARY_BODIES = [
    1000000,
    1000001,
    1000002,
    4132650,
    6383287,
    9068826,
    9999998,
    9999999,
    10000000,
    10000001,
    13466350,
    14774764,
    18657499,
    18972631,
    21272789,
    50000000,
    60803000,
    76124890,
    99999998,
    99999999,
]

NON_STRING_INPUTS: list[Any] = [None, 0, 42, 189726317, True, False, [], {}, 1.5]

LITERAL_INPUTS = [
    "",
    " ",
    "\u00a0",
    "\t\n",
    "-",
    "-9",
    "0",
    "1",
    "7",
    "K",
    "k",
    "17",
    "1-9",
    "173",
    "1735",
    "17353",
    "1996",
    "1.234-5",
    "999.999-4",
    "0-0",
    "00.000.000-0",
    "00000000-0",
    "0000000000000000000000-0",
    "0018.972.631-7",
    "01.234.567-8",
    "123.456.789-0",
    "228298638-0",
    "1234567890123-K",
    "21.272789-K",
    "21272.789-K",
    "2.1272.789-K",
    "212.72.789-K",
    "21.272.789.K",
    "21..272.789-K",
    "21.272.789--K",
    "21.272.789-",
    "21.272.789",
    "-21.272.789-K",
    "18,972,631-7",
    "18*972*631-7",
    "18-972-631-7",
    "18 972 631 7",
    "18.972.631 - 7",
    "error18.972.631-7",
    "18.972.631-7error",
    "chuma1996@gmail.com",
    "1\u0668\u0669\u0667\u0662\u0666\u0663\u0661-7",
    "\u0661\u0668\u0669\u0667\u0662\u0666\u0663\u0661-7",
    "\ufeff189726317",
    "189726317\ufeff",
    "2127K2789",
    "21272789KK",
    "21272789k",
    "  21.272.789-K  ",
    "\u00a021.272.789-K\u00a0",
    "\n18972631-7\t",
    "18.972.631-7\n",
    "NaN",
    "1e7-4",
    "+18972631-7",
    "١٨٩٧٢٦٣١٧",
]


def variants(body: int) -> list[str]:
    plain = str(body)
    verifier = rut.get_verifier(plain)
    assert verifier is not None, plain
    dotted = f"{body:,}".replace(",", ".")
    wrong = "0" if verifier != "0" else "1"

    return [
        f"{dotted}-{verifier}",
        f"{plain}-{verifier}",
        f"{plain}{verifier}",
        f"{dotted}{verifier}",
        f"{dotted}-{verifier.lower()}",
        f" {dotted}-{verifier} ",
        f"{dotted}-{wrong}",
        f"{plain}{wrong}",
        f"0{dotted}-{verifier}",
        f"{plain}0-{verifier}",
    ]


def outcome(value: Any) -> dict[str, Any]:
    result = rut.safe_parse(value)

    if result.success:
        return {
            "outcome": "valid",
            "output": result.output,
            "dotted": rut.format(result.output),
            "plain": rut.format(result.output, style="plain"),
        }

    body_length = result.issue.body_length if result.issue.kind == "length" else None

    return {
        "outcome": result.issue.kind,
        "output": None,
        "bodyLength": body_length,
    }


def main() -> None:
    random.seed(20260925)
    bodies = list(BOUNDARY_BODIES)
    bodies.extend(random.randint(1_000_000, 99_999_999) for _ in range(20))

    inputs: list[Any] = list(NON_STRING_INPUTS)
    inputs.extend(LITERAL_INPUTS)
    for body in bodies:
        inputs.extend(variants(body))

    seen: set[str] = set()
    cases: list[dict[str, Any]] = []
    for value in inputs:
        key = f"{type(value).__name__}:{value!r}"
        if key in seen:
            continue
        seen.add(key)
        cases.append({"input": value, **outcome(value)})

    note = (
        "Generated by scripts/generate_conformance.py. Both test suites assert "
        "against it so the two implementations cannot drift."
    )
    lines = [
        "{",
        f'  "note": {json.dumps(note)},',
        '  "cases": [',
    ]
    for index, case in enumerate(cases):
        comma = "," if index < len(cases) - 1 else ""
        lines.append(f"    {json.dumps(case, ensure_ascii=False)}{comma}")
    lines.extend(["  ]", "}", ""])

    FIXTURE.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(cases)} cases to {FIXTURE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
